const thaiConsonants = [
    { name: 'ก', romanization: 'ko kai', related: ['k'] },
    { name: 'ข', romanization: 'kho khwai', related: ['kh'] },
    { name: 'ฃ', romanization: 'kho khon', related: ['kh']},
    { name: 'ค', romanization: 'kho ra-khang', related: ['kh'] },
    { name: 'ฅ', romanization: 'kho khon', related: ['kh'] },
    { name: 'ฆ', romanization: 'kho rue-si', related: ['kh'] },
    { name: 'ง', romanization: 'ngo ngu', related: ['ng'] },
    { name: 'จ', romanization: 'jo jaan', related: ['j'] },
    { name: 'ฉ', romanization: 'cho ching', related: ['ch'] },
    { name: 'ช', romanization: 'cho chang', related: ['ch'] },
    { name: 'ซ', romanization: 'so so', related: ['s'] },
    { name: 'ฌ', romanization: 'cho chaa', related: ['ch'] },
    { name: 'ญ', romanization: 'yo ying', related: ['y'] },
    { name: 'ฎ', romanization: 'do cha-da', related: ['d'] },
    { name: 'ฏ', romanization: 'to pataak', related: ['t'] },
    { name: 'ฐ', romanization: 'tho than', related: ['th'] },
    { name: 'ฑ', romanization: 'tho montho', related: ['th'] },
    { name: 'ฒ', romanization: 'tho phuthao', related: ['th'] },
    { name: 'ณ', romanization: 'no nen', related: ['n'] },
    { name: 'ด', romanization: 'do dek', related: ['d'] },
    { name: 'ต', romanization: 'to tao', related: ['t'] },
    { name: 'ถ', romanization: 'tho thang', related: ['th'] },
    { name: 'ท', romanization: 'tho thahan', related: ['th'] },
    { name: 'ธ', romanization: 'tho thong', related: ['th'] },
    { name: 'น', romanization: 'no nu', related: ['n'] },
    { name: 'บ', romanization: 'bo baimai', related: ['b'] },
    { name: 'ป', romanization: 'po pla', related: ['p'] },
    { name: 'ผ', romanization: 'pho phan', related: ['ph'] },
    { name: 'ฝ', romanization: 'fo fa', related: ['f'] },
    { name: 'พ', romanization: 'pho phueng', related: ['ph'] },
    { name: 'ฟ', romanization: 'fo fan', related: ['f'] },
    { name: 'ภ', romanization: 'pho sam-phao', related: ['ph'] },
    { name: 'ม', romanization: 'mo ma', related: ['m'] },
    { name: 'ย', romanization: 'yo yak', related: ['y'] },
    { name: 'ร', romanization: 'ro ruea', related: ['r'] },
    { name: 'ล', romanization: 'lo ling', related: ['l'] },
    { name: 'ว', romanization: 'wo waen', related: ['w'] },
    { name: 'ศ', romanization: 'so rue-sii', related: ['s'] },
    { name: 'สร', romanization: 'so tsaa', related: ['s'] },
    { name: 'ห', romanization: 'ho hip', related: ['h'] },
    { name: 'อ', romanization: 'o ang', related: [] },
    { name: 'ฮ', romanization: 'ho nokhuk', related: [] }
];

export default thaiConsonants;